-- Generated by scripts/generate-auth-schema.mjs — do not edit by hand.
-- Regenerate after changing src/server/auth config or upgrading better-auth.

create table "user" (
  "id" text primary key not null,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" integer not null default 0,
  "image" text,
  "createdAt" date not null,
  "updatedAt" date not null,
  "role" text,
  "banned" integer default 0,
  "banReason" text,
  "banExpires" date
);

create table "session" (
  "id" text primary key not null,
  "expiresAt" date not null,
  "token" text not null unique,
  "createdAt" date not null,
  "updatedAt" date not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user"("id") on delete cascade,
  "impersonatedBy" text,
  "activeOrganizationId" text
);
create index "session_userId_idx" on "session" ("userId");

create table "account" (
  "id" text primary key not null,
  "issuer" text not null,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user"("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" date,
  "refreshTokenExpiresAt" date,
  "scope" text,
  "password" text,
  "createdAt" date not null,
  "updatedAt" date not null
);
create index "account_userId_idx" on "account" ("userId");
create unique index "account_issuer_accountId_uidx" on "account" ("issuer", "accountId");

create table "verification" (
  "id" text primary key not null,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" date not null,
  "createdAt" date not null,
  "updatedAt" date not null
);
create index "verification_identifier_idx" on "verification" ("identifier");

create table "organization" (
  "id" text primary key not null,
  "name" text not null,
  "slug" text not null unique,
  "logo" text,
  "createdAt" date not null,
  "metadata" text
);

create table "organizationRole" (
  "id" text primary key not null,
  "organizationId" text not null references "organization"("id") on delete cascade,
  "role" text not null,
  "permission" text not null,
  "createdAt" date not null,
  "updatedAt" date
);
create index "organizationRole_organizationId_idx" on "organizationRole" ("organizationId");
create index "organizationRole_role_idx" on "organizationRole" ("role");

create table "member" (
  "id" text primary key not null,
  "organizationId" text not null references "organization"("id") on delete cascade,
  "userId" text not null references "user"("id") on delete cascade,
  "role" text not null default 'member',
  "createdAt" date not null
);
create index "member_organizationId_idx" on "member" ("organizationId");
create index "member_userId_idx" on "member" ("userId");

create table "invitation" (
  "id" text primary key not null,
  "organizationId" text not null references "organization"("id") on delete cascade,
  "email" text not null,
  "role" text,
  "status" text not null default 'pending',
  "expiresAt" date not null,
  "createdAt" date not null,
  "inviterId" text not null references "user"("id") on delete cascade
);
create index "invitation_organizationId_idx" on "invitation" ("organizationId");
create index "invitation_email_idx" on "invitation" ("email");
