ALTER TABLE jobs ADD COLUMN address_postal TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN address_prefecture TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN address_city TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN address_rest TEXT NOT NULL DEFAULT '';